version: '3.8'
services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5431:5432
  pgadmin: 
    image: dpage/pgadmin4:8
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: eamartinez.acelas@gmail.com
      PGADMIN_DEFAULT_PASSWORD: qwerty
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8080:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db